### ISSUE TITLE
Dot product

### ISSUE THREAD

**Issue by yay** [rust-lang/packed_simd#283]
Hi,

Is there a way to calculate a dot product with this library? For example, in Swift I would do:
```swift
let ray_direction = SIMD3<Double>(1, 2, 3)
let outward_normal = SIMD3<Double>(4, 5, 6)
let front_face = dot(ray_direction, outward_normal) <= 0
```

I found this snippet of code but it operates on slices, not `f64x4`:
https://github.com/rust-lang/packed_simd/blob/master/examples/dot_product/src/simd.rs

**Comment by GabrielMajeri** [comment]
The thing is, if you need to compute the dot product for a small number of vectors, [it's probably better not to use SIMD intrinsics](https://stackoverflow.com/questions/47405717/dot-product-of-vectors-with-simd). 

In the referenced example, it makes sense to use it on slices, because there the increased latency is worth the much greater throughput. 

In your Swift example, it's better to write a manual `dot` computation. Providing wrappers to high-level mathematical operations falls outside the scope of this crate; you might want to look into something like [cgmath](https://github.com/rustgd/cgmath).

**Comment by yay** [comment]
Makes sense, thank you for the explanation. I suspected there might be a good reason it's not included, since the library is quite comprehensive.
