### ISSUE TITLE
Fail to compile packed_simd on windows

### ISSUE THREAD

**Issue by panzan** [rust-lang/packed_simd#285]
```
   Compiling packed_simd v0.3.3
error: internal compiler error: src\librustc_traits\normalize_erasing_regions.rs:37: could not fully normalize `<A as sealed::SimdArray>::Tuple`

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (4fb54ed48 2020-06-14) running on x86_64-pc-windows-msvc

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `packed_simd`.

To learn more, run the command again with --verbose.
```

**Comment by ZhouXiaolin** [comment]
me too,on mac .

`
error: internal compiler error: src/librustc_traits/normalize_erasing_regions.rs:37:32: could not fully normalize `<A as sealed::SimdArray>::Tuple`

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:912:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.46.0-nightly (2935d294f 2020-06-17) running on x86_64-apple-darwin

note: compiler flags: -C opt-level=3 -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C target-cpu=native --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error; 18 warnings emitted

error: could not compile `packed_simd`.
`

**Comment by alecmocatta** [comment]
This is https://github.com/rust-lang/rust/issues/73249 and was fixed by https://github.com/rust-lang/rust/issues/73537.

**Comment by Lokathor** [comment]
@panzan or @ZhouXiaolin can either of you confirm if the crate is fixed within your envrionments?

**Comment by gilescope** [comment]
That version works for me on windows (1.45 nightly). I really need to upgrade that nightly :-)
I think we can close this now.

**Comment by JohnTitor** [comment]
Also works on my end, closing as fixed.
